include/votca/tools/vec.h

Rewrote vec class to have accessors like vec[2] by using an unamed union

added [] operator to vector class using unnamed union

---

.travis.yml
CMakeModules/gitversion.cmake

Switch CI to Docker

---

include/votca/tools/edge.h
src/libtools/edge.cc
src/tests/CMakeLists.txt
src/tests/test_edge.cc

Edge Class is a general class for describing the relationship between two vertices or points. It is more specific then just a pair class, it makes use of underlying pair class
(p1,p2)
1. Stores two int values 
2. Smaller int is always put in p1 location
3. Allows sorting and hashes 
Useful for describing graphs, bonds, links molecular structures etc....

Edge class

---

include/votca/tools/elements.h
src/tests/test_elements.cc

This fix is to make the file compatible to https://github.com/votca/xtp/pull/75
@JensWehner @zetadin

Fix for elements.h file 

---

.travis.yml
include/votca/tools/typeconverter.h
src/tests/CMakeLists.txt
src/tests/test_typeconverter.cc

Added type converter class provides the ability to convert between complex types without the need for cross linking multiple header files.

Type Converter class

---

include/votca/tools/matrix.h
src/tests/CMakeLists.txt
src/tests/test_matrix.cc

Not having an ==/!== operators for the matrix was annoying so I added one with a little testing.

Matrix update testing

---

src/libtools/edge.cc
src/tests/test_edge_base.cc

Small update make use of std::minmax function to sort internals of edge.

Update edge class

---

include/votca/tools/application.h
include/votca/tools/elements.h
include/votca/tools/property.h
include/votca/tools/vec.h
netbeans/libtools/nbproject/Makefile-impl.mk
netbeans/libtools/nbproject/configurations.xml
src/libtools/application.cc
src/libtools/property.cc
src/tests/CMakeLists.txt
src/tests/test_vec.cc

Added isClose to vec class,
added unittest for vec
fixed Warning in elements.h
prepared all tools dependencies of vec.h for removal of using namespace std: in vec.h. Retained because ctp fails if using namespace is removed

Vector close feature

---

.travis.yml
netbeans/libtools/nbproject/configurations.xml
src/libtools/property.cc

Parser in property.cc was not released resulting in a memleak.

fixed mem leak and updated netbeans project xml

---

include/votca/tools/elements.h
netbeans/libtools/nbproject/configurations.xml
src/tests/test_elements.cc

added a new table for electronic polarizabilities to elements.h

New elements table

---

include/votca/tools/datacollection.h
src/tests/CMakeLists.txt
src/tests/test_datacollection.cc

Adding tests:
1. cleaning up code
2. To enable removal of histogram class must understand the different components

Enhancement test datacollection

---

include/votca/tools/graph.h
src/libtools/graph.cc
src/tests/test_graph_base.cc

2. Added testing of the the method

1. Added the rest of incomplete method to graph source file

---

include/votca/tools/matrix.h

Check the first commit for the actual code that I changed, Everything in the second commit is simply a result of google formatting changes. 
Fix #51

Enhancement add bounds checking matrix

---

CMakeLists.txt
netbeans/libtools/nbproject/configurations.xml
src/libtools/property.cc
src/tests/CMakeLists.txt

before: `<value attr1="bla">              </value>`
now:    `<value attr1="bla"/>`

property now outputs empty xml property strings without offset

---

include/votca/tools/objectfactory.h

is not used anywhere and we do not really want macros flying around

removed factory macro

---

include/votca/tools/property.h

-Property can now directly convert to Eigen::Vector3d and Eigen::VectorXd
I tried to get a more general implementation but as far as I know I cannot partially specialize the templated function

property can now convert to some eigen structures

---

src/libtools/application.cc

fixes https://github.com/votca/xtp/issues/163
fixes https://github.com/votca/ctp/issues/100

test if enviroment variable is set

---

netbeans/libtools/nbproject/configurations.xml
src/tests/CMakeLists.txt
src/tests/test_property.cc

forgot to add test to https://github.com/votca/tools/pull/72

added test

---

include/votca/tools/datacollection.h
src/tests/test_datacollection.cc

Tested methods of data collection class more thoroughly.

Added more test to datacollection

---

include/votca/tools/graph.h
src/libtools/graphalgorithm.cc

rewrote subdivison and it fixes https://github.com/votca/csg/issues/319
do not know exactly why

Bugfix findsubgraphs

---

include/votca/tools/graphalgorithm.h
src/tests/test_graphalgorithm.cc

Adds unit testing for decoupleSubGraphs function call.

Decouple sub graphs add tests

---

include/votca/tools/elements.h
netbeans/libtools/nbproject/configurations.xml
netbeans/libtools/nbproject/project.xml
src/libtools/elements.cc
src/tests/test_elements.cc

Throws error if you request mass of an unknown element

improved warnings for elements

---

include/votca/tools/vec.h
src/libtools/table.cc

switched lexical_cast<double> to stod

---

include/votca/tools/eigen.h

include also sparse part of the library

---

.gitlab-ci.yml
src/tools/votca_property.cc

Part of https://github.com/votca/votca/pull/127

Add formatting check to CI

---

.codecov.yml
.travis.yml

Part of https://github.com/votca/votca/pull/132

Improve codecov coverage

---

.gitlab-ci.yml

Part of https://github.com/votca/votca/pull/134

.gitlab-ci.yml: add rawhide builds

---

scripts/votca_compare.in

Part of https://github.com/votca/csg/issues/341

votca_compare: move to python3

---

include/votca/tools/graph.h
src/libtools/graph.cc

Attempt to fix problem:
https://groups.google.com/forum/#!msg/votca/LGjDJLwuFgI/EnM4zFvJBQAJ

Attempt at fixing compile problem

---

netbeans/libtools/nbproject/configurations.xml
src/libtools/CMakeLists.txt

Reduces scope of many library symbols

Target link lib

---

include/votca/tools/unitconverter.h
src/tests/CMakeLists.txt
src/tests/test_unitconverter.cc

Class for helping the io readers in csg convert between different units.

Added tests for unitconverter

---

include/votca/tools/constants.h

https://github.com/votca/csg/compare/electrostatics...electrostatics-fix-lammpsdumpreaderwriter
Added two constants to deal with conversion of energy units from kcal to kj

Added energy conversion units

---

include/votca/tools/correlate.h
include/votca/tools/crosscorrelate.h
include/votca/tools/cubicspline.h
include/votca/tools/datacollection.h
include/votca/tools/histogram.h
include/votca/tools/objectfactory.h
include/votca/tools/parsexml.h
include/votca/tools/rangeparser.h
include/votca/tools/table.h
netbeans/libtools/nbproject/configurations.xml
netbeans/libtools/nbproject/project.xml
src/libtools/correlate.cc
src/libtools/crosscorrelate.cc
src/libtools/datacollection.cc
src/libtools/histogram.cc
src/libtools/parsexml.cc
src/libtools/rangeparser.cc
src/libtools/table.cc
src/libtools/tokenizer.cc
src/tools/votca_property.cc

removes all using namespace  from include headers, merge after https://github.com/votca/csg/pull/409

fix includes

---

include/votca/tools/akimaspline.h
include/votca/tools/colors.h
include/votca/tools/cubicspline.h
include/votca/tools/graph_bf_visitor.h
include/votca/tools/graph_df_visitor.h
include/votca/tools/graphdistvisitor.h
include/votca/tools/linspline.h
include/votca/tools/parsexml.h
include/votca/tools/reducedgraph.h
src/tests/test_graphvisitor.cc
src/tests/test_thread.cc
src/tools/votca_property.cc

added overwrite specifiers https://en.cppreference.com/w/cpp/language/override

added overwrite specifiers

---

CMakeLists.txt
include/votca/tools/correlate.h
include/votca/tools/crosscorrelate.h
include/votca/tools/datacollection.h
include/votca/tools/eigen.h
include/votca/tools/votca_config.h.in
netbeans/libtools/nbproject/configurations.xml
src/libtools/CMakeLists.txt
src/libtools/VOTCA_TOOLSConfig.cmake.in
src/libtools/correlate.cc
src/libtools/crosscorrelate.cc
src/libtools/datacollection.cc
src/libtools/globals.cc
src/libtools/histogram.cc
src/libtools/linalg.cc
src/tests/CMakeLists.txt
src/tests/test_correlate.cc
src/tests/test_crosscorrelate.cc

implements https://github.com/votca/tools/issues/181
Part of https://github.com/votca/votca/pull/219
Fix #181 
Related to https://github.com/votca/csg/issues/104

Fft rewrite

---

include/votca/tools/property.h
src/tests/test_property.cc
src/tests/test_tokenizer.cc

more unit tests for tokenizer and property

Prop tok tests

---

include/votca/tools/types.h
src/libtools/edge.cc
src/libtools/graph.cc

Related to https://github.com/votca/xtp/issues/339

changed long int to Eigen::Index

---

include/votca/tools/unitconverter.h
src/tests/test_unitconverter.cc

Added more units, force, and velocity units as well as intrinsic and extrinsic energy and force units
Added tests for force and velocity
Simplified functions

Piece wise add more units

---

CMakeModules/FindMKL.cmake

FindMKL.cmake: fix target creation

---

CHANGELOG.md
include/votca/tools/unitconverter.h
src/libtools/edgecontainer.cc
src/libtools/graph.cc
src/libtools/graph_bf_visitor.cc
src/libtools/graphalgorithm.cc
src/libtools/property.cc
src/libtools/reducedgraph.cc
src/tests/test_graphalgorithm.cc

fix clang 10 warnings

---

CHANGELOG.md
scripts/VOTCARC.bash.in
scripts/VOTCARC.csh.in

Reported here: https://groups.google.com/d/msg/votca/GymfBemqbdo/jVmlYxQdBQAJ

VOTCARC.*: there are no more rc files

---

include/votca/tools/akimaspline.h
include/votca/tools/application.h
include/votca/tools/average.h
include/votca/tools/calculator.h
include/votca/tools/cubicspline.h
include/votca/tools/datacollection.h
include/votca/tools/edgecontainer.h
include/votca/tools/elements.h
include/votca/tools/graph.h
include/votca/tools/graphvisitor.h
include/votca/tools/histogram.h
include/votca/tools/linspline.h
include/votca/tools/property.h
include/votca/tools/rangeparser.h
include/votca/tools/reducededge.h
include/votca/tools/table.h
src/libtools/histogram.cc
src/libtools/property.cc

use new clang tidy checks

---

.github/workflows/format.yml
CHANGELOG.md

This won't work before actions got added to master.

GH Actions: add format action

---

CHANGELOG.md
CMakeLists.txt
include/votca/tools/eigen.h
src/libtools/CMakeLists.txt

cmake: don't use fftw3 if mkl was found

---

CHANGELOG.rst
include/votca/tools/random.h

fix https://github.com/votca/tools/issues/262

cast to unsigned and added exception

---

CHANGELOG.md
include/votca/tools/unitconverter.h

Need this change as the base container is now F32.

format code with clang-10

---

CHANGELOG.rst
CMakeModules/FindMKL.cmake

to find distribution installed MKL automatically.

added path to find mkl

---

.github/workflows/continuous-integration-workflow.yml
CHANGELOG.rst
include/votca/tools/objectfactory.h
src/tests/CMakeLists.txt
src/tests/test_objectfactory.cc

https://github.com/votca/votca/pull/487

For/factory ptr/ptr

---

include/votca/tools/property.h
src/libtools/property.cc
src/tests/test_property.cc

now you can add a property to another property and the paths are automatically updated.

added a add(Property) function to property

---

CHANGELOG.rst
include/votca/tools/application.h
include/votca/tools/colors.h
include/votca/tools/globals.h
include/votca/tools/property.h
include/votca/tools/propertyiomanipulator.h
src/libtools/application.cc
src/libtools/globals.cc
src/libtools/property.cc
src/libtools/propertyiomanipulator.cc
src/tools/votca_property.cc

Fix https://github.com/votca/tools/issues/326
blocked by https://github.com/votca/xtp/pull/655
@junghans did I miss anything?

removed tex and man output

---

CHANGELOG.rst
share/doc/index.rst
share/doc/reference.rst

Improvement of https://www.votca.org/tools/reference.html
@JensWehner, should every program have its own html page instead of list all 3 tools in one page?

doc: make programs as subsections

---

CHANGELOG.rst
scripts/votca_help2doc.in

* remove author and copyright from rst #331 
* fix example section #327

minor fixes for votca_help2doc script

---

CHANGELOG.rst
scripts/votca_help2doc.in

fix rst format

---

CHANGELOG.rst
CMakeLists.txt
scripts/VOTCARC.bash.in
scripts/VOTCARC.csh.in

For https://github.com/votca/xtp/pull/673

VOTCARC: export PYTHONPATH

---

CHANGELOG.rst
scripts/votca_help2doc.in

* fix #339  by updating the python script that generates the rst files

Help rst man

---

CHANGELOG.rst
CMakeModules/FindMKL.cmake

FindMKL.cmake: fix ThreadLinkage

---

CHANGELOG.rst
include/votca/tools/objectfactory.h

Made the factory more general to take also be able to construct objects which are not default constructible but need constructor arguments.

factory can take other constructors now
