- include/votca/tools/name.h
- src/tests/CMakeLists.txt
- src/tests/test_name.cc
Designed to used in larger objects across votca should provide uniform methods for setting and getting object names.
> Name object

- src/libtools/edgecontainer.cc
- src/tests/test_table.cc
I did not realize I was misusing lexical cast until Victor pointed it out with the matrix pull request. Then I remembered I had used it elsewhere for converting between types where I should of simply used static_cast  seeing as I was not converting between strings.
> removed use of boost namespace

- src/libtools/graph.cc
- src/libtools/graphalgorithm.cc
- src/tests/test_graph_bf_visitor.cc
- src/tests/test_graphalgorithm.cc
Error was caused from using a for range loop with a vector while also skipping vertices occasionally. The for loop was not ending correctly and thus was trying to access memory outside of the vector memory block. 
Fix #60
> Fixed memory error

- include/votca/tools/graph.h
- include/votca/tools/graphnode.h
- include/votca/tools/name.h
Reducing differences between the setName and getName functions found in most of the structures. References are also supposed to yield better performance.
> Refactor name class

- include/votca/tools/matrix.h
- include/votca/tools/vec.h
- src/tests/test_matrix.cc
- src/tests/test_vec.cc
A small interface from tools::matrix to Eigen::Matrix3d and back, same also for vec to Eigen::Vector3d. It is all done by copy. No fancy unions or so, because it is only a temporary solution till we fully switch to Eigen structures and this keeps the ownership clean
> added constructors conversion functions and tests

- include/votca/tools/elements.h
- netbeans/libtools/nbproject/configurations.xml
- src/libtools/elements.cc
- src/tests/test_elements.cc
before the all elements maps were filled and then `const` querries could request info,
now elements is not filled in the beginning, if one info is request, the relevant map is filled and the element returned, queries to the same map will then request from the filled map.
> elements.h now caches elementsinfo only when the method is called once

- include/votca/tools/table.h
- src/tests/test_table.cc
It was found that the 
```
Table(Table &tbl); 
```
Constructor was causing resize before initializing the vectors, for some reason this was causing an invalid write error. It was solved by simply removing the resize call which was redundant anyway as the vectors are simply copied over anyway.
> Enhanced testing table debugging invalid memory write

- include/votca/tools/edge.h
- src/libtools/property.cc
avoids memory leak, because otherwise if file does not exist parser is not freed.
> changed order so parser does not get initialized if file does not exist

- include/votca/tools/edge.h
- include/votca/tools/graph.h
- include/votca/tools/graph_bf_visitor.h
- include/votca/tools/graph_df_visitor.h
- include/votca/tools/graphalgorithm.h
- include/votca/tools/graphdistvisitor.h
- include/votca/tools/graphvisitor.h
- src/libtools/edge.cc
- src/libtools/edgecontainer.cc
- src/libtools/graph_bf_visitor.cc
- src/libtools/graph_df_visitor.cc
- src/libtools/graphalgorithm.cc
- src/libtools/graphdistvisitor.cc
- src/libtools/graphvisitor.cc
- src/tests/test_graphalgorithm.cc
This branch includes an algorithm that will explore a chosen branch within a graph. If you were to choose a vertex within the graph and pick one of the edges connected to vertex and explore all the way down the tree from that point on you would explore the branch. In the case that the exploration returns back to the vertex it will not continue past the starting point. 
E.g. If I have a graph
<pre>
1 - 2 - 3 - 4 
|   |
5 - 6
</pre>
And my starting vertex is two and I set the branch to explore by specifying edge 1 - 2. I would end up with a branch that looked like this:
<pre>
1 - 2 
|   |
5 - 6
</pre>
The purpose of doing this is it provides the basis for defining functionality to resolve this structural components of molecules. 
Should only be merged after: …
> Feature explore branch algorithm

- include/votca/tools/edgecontainer.h
- include/votca/tools/graph.h
- include/votca/tools/graph_bf_visitor.h
- include/votca/tools/graph_df_visitor.h
- include/votca/tools/graphalgorithm.h
- include/votca/tools/graphvisitor.h
- include/votca/tools/reducededge.h
- include/votca/tools/reducedgraph.h
- src/libtools/edgecontainer.cc
- src/libtools/graph.cc
- src/libtools/graph_bf_visitor.cc
- src/libtools/graph_df_visitor.cc
- src/libtools/graphalgorithm.cc
- src/libtools/graphvisitor.cc
- src/libtools/reducedgraph.cc
- src/tests/test_edgecontainer.cc
- src/tests/test_graph_base.cc
- src/tests/test_graphalgorithm.cc
- src/tests/test_graphvisitor.cc
- src/tests/test_reducedgraph.cc
This branch corrects a bug found in the graph_df_visitor class, it also adds extra functionality to the reducedGraph namely the ability to expand and return the full graph. This pull request should only be merged after https://github.com/votca/tools/pull/95.
> Add expand graph method to reduced graph

- include/votca/tools/identity.h
- include/votca/tools/name.h
- src/tests/test_identity.cc
- src/tests/test_name.cc
Simply, changed out exception handling for assertions since the classes will not be used by the end user directly.
> Removed use of exception handling from name and identity classes

- CMakeLists.txt
- src/tests/CMakeLists.txt
Forgot to use the new branch naming convention.
Fix #104
> cmake: lower boost version a bit for epel7

- include/votca/tools/constants.h
- src/tests/CMakeLists.txt
- src/tests/test_constants.cc
Adding explicit constants for dealing with molecule, residue, element type and ids when they have not been assigned.
> Add constants

- src/tools/CMakeLists.txt
Doing this will allow us to separate the different tests e.g.
ctest -R unit
ctest -R integration
ctest -R memory
> Prepended integration to votca_property

- src/tests/CMakeLists.txt
- src/tools/CMakeLists.txt
Add labels to appropriate tests to help separate and run different test groups.
> Added labels

- src/tests/CMakeLists.txt
Needs to be done in xtp as well, but https://github.com/votca/xtp/pull/277 include that fix already.
> cmake: Boost_UNIT_TEST_FRAMEWORK_LIBRARY -> Boost::unit_test_framework

- include/votca/tools/calculator.h
- include/votca/tools/globals.h
- src/libtools/application.cc
- src/libtools/calculator.cc
- src/libtools/globals.cc
I removed the `bool votca::tools::globals::verbosity` which was a global and replaced it by 
a struct `Log` with an enum `enum Level{error,warning,debug,info}` in the `votca` namespace 
the global variable is `votca::Log::current_level` 
the most used command from before 
`if (votca::tools::globals::verbose)` is now replaced by `if(votca::Log::current_level>0)`
I need opinions if that is okay.
higher logging levels are then activated by specifying `--verbose` `--verbose1` `--verbose2` on the command line. `-v` is short for `--verbose2`. @junghans  is that okay for you?
boost::program options only supports one character short options.
> verbosity levels

- CMakeLists.txt
Reverts votca/tools#205
Needs to be done on the votca/votca level
> Revert "cmake: inject --no-as-needed for mkl + gcc"

- CHANGELOG.md
- include/votca/tools/eigen.h
- src/libtools/crosscorrelate.cc
Non-system fftw will lead to a missing 'fftw.h' when building
excutables as fftw is only a private dependcies and hence the
fftw include path is missing. Don't include fft header in
eigen.h, so it won't get pull in for every executable.
Reported here:
https://groups.google.com/d/msg/votca/wFNG1mmKwSU/hOS1zplRDQAJ
> fix build with non-system fftw

- CHANGELOG.md
- src/libtools/calculator.cc
- src/tests/test_calculator.cc
Allow the `Calculator` choices to have multiple values.
Current options for choices are:
* Either `float,float+,int,int+,bool`
* One of several possible values like foo, bar, etc.
This PR allows the choices to take multiple values out of multiple possible options,
for instances:
values: `[qux,bar]`
choices: `[foo,bar,baz,qux]`
> allow calculator choices to have several possible value

- CHANGELOG.md
- include/votca/tools/calculator.h
- src/libtools/calculator.cc
- src/tests/test_calculator.cc
1) Currently, in the XML files containing the `Calculators` options, the default and the option value are the same, but the defaults are only used for documentation purposes. In this PR we change that behaviour but allowing the XML to only define the defaults, leaving empty the values. A new `Calculator::InjectDefaultsAsValues` has been implemented to fill in the values.
2) We want to allow the options to take a single value out of a choice set, for example:
```
<option1 default="foo" choices="foo, bar"></option1>
```
But we also want to allow for the options to take multiple options out of multiple choices. The following syntax has been implemented for this case:
```
<option2 default="foo, qux" choices="[foo, bar, qux]"></option1>
```
Notice the brackets in the `choices` attribute.
> inject defaults into calculators values

- CHANGELOG.md
- include/votca/tools/calculator.h
- src/libtools/calculator.cc
- src/tests/test_calculator.cc
Following the new standard proposed in #241, only the `default` attribute contains information and the values are empty for the default `XML` files. When merging the `default` options with the `user` options, some of the user's values may be empty, resulting in a `Property` object that contains some empty values even though they have a well-defined default.
Only overwrite the default values if the `user input` is non-empty.
> update option only if new value is not empty

- include/votca/tools/votca_config.h.in
the openmp part is not used in tools, at least I think so.
> removed unused openmp define

- CHANGELOG.md
- include/votca/tools/globals.h
- src/libtools/globals.cc
the function is not really reliable in detecting the xtp problem. Delete the whole variable because the include is problematic
> removed global mkl from globals to clear up include structure

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.rst
- README.rst
Not needs as this will be built on `votca/votca` immediately after each PR.
> CI: do not build for master

- CHANGELOG.rst
- scripts/votca_help2doc.in
* fix #346 
@junghans  locally I can only see a remaining warning:
```
votca/build/sphinx/csg/csg_orientcorr.rst:19: WARNING: Definition list ends without a blank line; unexpected unindent.
```
That warning is due to the equation in the description:
```
Calculates the orientational correlation function
<3/2*u(0)*u(r) - 1/2>
for a polymer melt, where u is the vector pointing along a bond and
r the distance between bond segments (centered on middle of bond).
```
Any suggestions about it?
> Help rst man

- CHANGELOG.rst
- include/votca/tools/average.h
std::sqrt is used in average.h but cmath is not included this fixes the problem.
> Joshua s brown/fix missing include

- CHANGELOG.rst
- src/tests/test_graphalgorithm.cc
Header unused and was causing problems for clang compilers as it was an extension specific to GNU compilers.
> Remove unused header

- CHANGELOG.rst
- include/votca/tools/NDimVector.h
- src/tests/CMakeLists.txt
- src/tests/test_NDimVector.cc
This basically allows you to replace all the std::vector<std::vector<std::vector<T>> > things with a nicer interface, it should also be faster because it avoids a lot of pointer indrection for higher dimensions.
For numbers this should not be used because Eigen::Tensor is much better, but for other things which have to be stored on a regular grid for example this is nice.
> added a NDim vector class

- include/votca/tools/lexical_cast.h
- include/votca/tools/property.h
- include/votca/tools/tokenizer.h
- src/libtools/calculator.cc
- src/libtools/property.cc
- src/libtools/rangeparser.cc
- src/libtools/table.cc
- src/tests/test_property.cc
- src/tests/test_tokenizer.cc
- src/tools/votca_property.cc
Made the string to type conversion much more powerful. Now `as<type>()` can be `bool` any numeric type or any kind of object that is constructible from a string and also a `std::vector<T>` of any of the above mentioned types, also Eigen::VectorXd Eigen::VectorXf and Eigen::Vector3d and Eigen::Vector3f are supported. 
Furthermore you can now delete Attributes and Children, although the later invalidates all pointers to child nodes. 
If we wanted we could go back to use a std::list underneath, instead of a std::vector and then all references would be valid, but then large xml files would take ages to load.
> Propery extensions

- CHANGELOG.rst
- include/votca/tools/property.h
- src/libtools/property.cc
- src/tests/test_property.cc
All a new add function which allows to add with `a.b.c` tag instead of just direct children
> add a add which can use . inside
